version: '3.3'
services:
  db:
      image: mysql:8.0.36
      ports:
        - "3309:3306"
      environment:
        MYSQL_DATABASE: 'spatial_test'
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_ALLOW_EMPTY_PASSWORD: 1